# Generated by Django 5.1 on 2024-11-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
