# Generated by Django 5.1.2 on 2024-11-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_orderdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdb',
            old_name='Message',
            new_name='Messages',
        ),
        migrations.RenameField(
            model_name='orderdb',
            old_name='Mobile',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='orderdb',
            old_name='TotalPrice',
            new_name='TotalAmount',
        ),
    ]
